### ISSUE TITLE
Wish you had made it identical to MacOS!

### ISSUE THREAD

**Issue by nashinwalker** [Dinno-DEV/zen-minimal-exit-menu#1]
I like the MacOS exit menu. It's similar, but not quite the same. Could you please make it identical to MacOS? Alternatively, if you'd prefer to stick with this design, would you consider creating another version for those of us who love the MacOS one?

**Comment by Dinno-DEV** [comment]
Sure, though I might not be able to use the MacOS' icons. Is that fine?

**Comment by nashinwalker** [comment]
> Sure, though I might not be able to use the MacOS' icons. Is that fine?

Thanks. Sure.

**Comment by Dinno-DEV** [comment]
The theme is updated and it's pending on the theme store PR 👍
